
services:
  websocket-server:
    build: .
    ports:
      - "3005:3005"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3005
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped